[tool.poetry]
name = "upstash_ratelimit_a"
version = "0.1.3"
description = ""
authors = ["Zgîmbău Tudor <tudor.zgimbau@gmail.com>"]
readme = "README.md"
packages = [{include = "upstash_ratelimit"}]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.3.0"
pytest-asyncio = "^0.21.0"
upstash-redis-a = "^0.1.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
